language: node_js
node_js:
  - "12"
install:
 - npm install
before_script:
 - bash ./scripts/setup-rc
script:
 - npm run lint
 - npm run test
after_script:
 - bash ./scripts/remove-rc
cache:
 directories:
   - "node_modules"