#!/bin/bash

# installation
npm install -g ganache-cli truffle

# run local ganache node
ganache-cli &
sleep 5
truffle migrate --reset --network local

# truffle test

# ava tests
ava test/* --verbose

# cleanup
pkill -f ganache 
