#!/bin/bash

# lint
npm run lint

# installation
npm install -g ganache-cli truffle

# setup
truffle develop /dev/null 1> /dev/null &
sleep 5
rm -rf build
truffle migrate --network local

# ava
ava test/registry.js --verbose
ava test/util.js --verbose

# cleanup
kill -9 $(lsof -t -i:8545)
